### ISSUE TITLE
Possibly provide more information on the VSCode page.

### ISSUE THREAD

**Issue by BitesizedLion** [Ciavarella/mpm-extension-vscode#3]
Hey there, if possible could you provide more information on the VSCode page? I installed it and set my key or what it now is given to me from the page. It does not stop my music or do anything basically. And the settings I was unable to find any information on at all.

**Comment by Ciavarella** [comment]
Sorry @BitesizedLion you are correct! I need to provide more information. The extension does not start by default. You need to type mpm in the command palette.  I have updated the readme. Thanks for the feedback!

**Comment by BitesizedLion** [comment]
Hey there again, by command palette you mean the bar that comes up when you press F1? If so I've done that and it comes up with the seconds counter down at the status bar but it does not count my seconds when typing anymore after i reinstalled it and authorized the spotify app and entered the token.

**Comment by Ciavarella** [comment]
Hi @BitesizedLion. Yes that is correct, do you have the Spotify application installed or are you running it in your browser? You must have the Spotify application installed. Im sorry for the inconvenience, i am quite new to programming and this is a school project, also my first extension. I checked the backend, could you please try and reload it one more time and let me know if it works?

**Comment by BitesizedLion** [comment]
Hello, I have the desktop Spotify application for Windows 10.

**Comment by BitesizedLion** [comment]
And I also reloaded it and such. And I just tried the extension for fun hah.

**Comment by BitesizedLion** [comment]
Just noticed it's working now! :)

**Comment by BitesizedLion** [comment]
But it does not stop the uh music when I reach 0 but it does take the seconds away. :)

**Comment by BitesizedLion** [comment]
Well uh, now it doesn't stop taking it away when I pause a bit strange.

**Comment by Ciavarella** [comment]
Haha thats great! :) I really don't think anyone is going to be using this extension seriously. They will probably just try it for fun. If it does not stop try typing just for like 2 seconds and see if it stops when the counter goes down to 0 again. If you manually press pause in Spotify it "overrides" and pauses the music. The counter does not stop. I published this today so i probably still have some bugs to fix, thanks for all the feedback and trying it out for me, much appreciated!

**Comment by BitesizedLion** [comment]
No problem! I am a pretty new developer as well, it would be fun if some people used it though. I saw it whilst I was scrolling through the marketplace. It doesn't stop going down though I hope you resolve all the bugs :)

**Comment by Ciavarella** [comment]
Thanks a lot @BitesizedLion ! I will let you know when its ready to go! 👍 Btw, congratz on being the first one to try it out 🥇

**Comment by amkhrjee** [comment]
> Just noticed it's working now! :)

How did you make it work? I entered the token in the Command Palette, but it doesn't seem to do anything.

**Comment by wolfram77** [comment]
@Ciavarella I think it is not working for me as well. It open up the Spotify app in Ubuntu, but does not play. Maybe some command-line arguemnts have changed since april 2019?

**Comment by Ciavarella** [comment]
> @Ciavarella I think it is not working for me as well. It open up the Spotify app in Ubuntu, but does not play. Maybe some command-line arguemnts have changed since april 2019?

Have you run the command ">Music Per Minute" in VSCode @wolfram77 ?

**Comment by wolfram77** [comment]
Yes, and it says Music Per Minute started. And i have also entered the spotify token from https://ciavarella.dev/auth/login

**Comment by Ciavarella** [comment]
> Yes, and it says Music Per Minute started. And i have also entered the spotify token from https://ciavarella.dev/auth/login

Does it say how many seconds left when you start typing? Does it add seconds when type? @wolfram77

**Comment by wolfram77** [comment]
Ok sorry, i see it now, and yes it adds. But it drops in steps of 3 seconds every second.
![Screenshot from 2020-05-25 14-17-59](https://user-images.githubusercontent.com/3179612/82796102-9c205580-9e92-11ea-9117-970de01aa7dd.png)

**Comment by Ciavarella** [comment]
> Ok sorry, i see it now, and yes it adds. But it drops in steps of 3 seconds every second.
> ![Screenshot from 2020-05-25 14-17-59](https://user-images.githubusercontent.com/3179612/82796102-9c205580-9e92-11ea-9117-970de01aa7dd.png)

And it never starts to play @wolfram77 ? Do you have Spotify Premium?

**Comment by wolfram77** [comment]
Tried: 
- Started a song, and it didnt pause after timeout.
- Kept it paused, and it didnt start.
- Closed spotify and typed.

No, i dont have a premium, i just registered today.
